version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    command: 'bash -c "./wait-for-it.sh db:5432 -q -- diesel setup && cargo watch -x run"'
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=loyalyt_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
